name: "Dev CI/CD"

on:
  workflow_dispatch:
  push:
    branches: [feature/*, release/*]
  pull_request:
    branches: [feature/*, release/*]

env:
  configuration: Release
  solution: EasyKeys.Veeqo.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          updateAssemblyInfo: false
          updateAssemblyInfoFilename: false

      - name: Display GitVersion outputs
        run: |
          echo "ShortSha: ${{ steps.gitversion.outputs.shortSha }}"
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "VersionSourceSha: ${{ steps.gitversion.outputs.versionSourceSha }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
          echo "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"

      - name: Install net10.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
            10.0.x
          include-prerelease: true
          
      - name: Clear Nuget Feeds
        run: dotnet nuget locals --clear all

      - name: Restore dependencies
        run: dotnet restore ${{ env.solution }} -v quiet

      # --- LINT (Run dotnet format and save output) ---
      - name: Lint (dotnet format)
        id: lint
        run: |
          dotnet format ${{ env.solution }} --verify-no-changes --severity error > lint-result.txt
          cat lint-result.txt

      # --- COMMENT BOT (Post lint results to PR) ---
      - name: Comment lint results on PR
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🧹 Lint Results
            ```
            ${{ steps.lint.outputs.lint-result }}
            ```
        env:
          # This next step loads the lint-result.txt content into an output variable for use in the comment
          lint-result: ${{ steps.lint.outputs.lint-result }}

      - name: Build
        run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }}  --no-restore -p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Test
        run: dotnet test --no-build --verbosity normal